import { ColourPalette } from "../models/pokemonAPIModels";

export const colorPalette: ColourPalette = {
    rock: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/rock.jpg')",
        backgroundNormalFrame: "url('/assets/images/normalFrameRock.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameRock.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameRock.png')",
    },
    fighting: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/fighting.jpg')",
        backgroundNormalFrame: "url('/assets/images/normalFrameFighting.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameFighting.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameFighting.png')",
    },
    electric: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/electric.avif')",
        backgroundNormalFrame: "url('/assets/images/normalFrameElectric.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameElectric.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameElectric.png')",
    },
    water: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/water.png')",
        backgroundNormalFrame: "url('/assets/images/normalFrameWater.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameWater.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameWater.png')",
    },
    grass: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/grass.jpg')",
        backgroundNormalFrame: "url('/assets/images/normalFrameGrass.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameGrass.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameGrass.png')",

    },
    fire: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/fire.jpg')",
        backgroundNormalFrame: "url('/assets/images/normalFrameFire.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameFire.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameFire.png')",
    },
    ghost: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/ghost.webp')",
        backgroundNormalFrame: "url('/assets/images/normalFrameGhost.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameGhost.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameGhost.png')",
    },
    ground: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/ground.jpg')",
        backgroundNormalFrame: "url('/assets/images/normalFrameGround.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameGround.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameGround.png')",
    },
    psychic: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/psychic.jpg')",
        backgroundNormalFrame: "url('/assets/images/normalFramePsychic.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFramePsychic.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFramePsychic.png')",
    },
    bug: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/Bug.jpg')",
        backgroundNormalFrame: "url('/assets/images/normalFrameBug.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameBug.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameBug.png')",
    },
    steel: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/steel.jpg')",
        backgroundNormalFrame: "url('/assets/images/normalFrameSteel.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameSteel.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameSteel.png')",
    },
    dragon: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/dragon.jpg')",
        backgroundNormalFrame: "url('/assets/images/normalFrameDragon.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameDragon.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameDragon.png')",
    },
    fairy: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/fairy.jpg')",
        backgroundNormalFrame: "url('/assets/images/normalFrameFairy.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameFairy.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameFairy.png')",
    },
    dark: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/dark.avif')",
        backgroundNormalFrame: "url('/assets/images/normalFrameDark.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameDark.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameDark.png')",
    },
    ice: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/ice.jpeg')",
        backgroundNormalFrame: "url('/assets/images/normalFrameIce.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameIce.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameIce.png')",
    },
    normal: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/normal.jpg')",
        backgroundNormalFrame: "url('/assets/images/normalFrameNormal.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameNormal.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameNormal.png')",
    },
    flying: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/flying.jpg')",
        backgroundNormalFrame: "url('/assets/images/normalFrameFlying.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFrameFlying.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFrameFlying.png')",
    },
    poison: {
        textColor: '#ffcc00',
        hueRotate: '',
        mainColor: '#ffcc00',
        backgroundImg: "url('/assets/images/poison.jpg')",
        backgroundNormalFrame: "url('/assets/images/normalFramePoison.png')",
        backgroundLegendaryFrame: "url('/assets/images/legendaryFramePoison.png')",
        backgroundMythicalFrame: "url('/assets/images/mythicalFramePoison.png')",
    },

};