export const typeIconMapping: { [key: string]: string } = {
    grass: '/assets/svg/grass-leaves-svgrepo-com.svg',
    poison: '/assets/svg/poison-svgrepo-com.svg',
    ice:'/assets/svg/mountain-part-2-svgrepo-com.svg',
    ghost:'/assets/svg/ghost-svgrepo-com.svg',
    dark:'/assets/svg/moonhalf-svgrepo-com.svg',
    fairy:'/assets/svg/butterfly-svgrepo-com.svg',
    rock:'/assets/svg/rock-svgrepo-com.svg',
    ground:'/assets/svg/earth-svgrepo-com.svg',
    psychic:'/assets/svg/crystal-ball-svgrepo-com.svg',
    fighting:'/assets/svg/fighting-svgrepo-com.svg',
    electric:'/assets/svg/electricity-svgrepo-com.svg',
    water:'/assets/svg/water-drops-svgrepo-com.svg',
    fire:'/assets/svg/fire-svgrepo-com.svg',
    steel:'/assets/svg/shield-antivirus-svgrepo-com.svg',
    bug:'/assets/svg/bug-svgrepo-com.svg',
    dragon:'/assets/svg/dragon-svgrepo-com.svg',
    normal:'/assets/svg/pokeball-pokemon-svgrepo-com.svg',
    flying:'/assets/svg/air-svgrepo-com.svg',
    // defense: '/assets/svg/shield-svgrepo-com (1).svg',
    // speed: '/assets/svg/racing-speed-svgrepo-com.svg',
    // 'special-attack': '/assets/svg/boxing-fight-svgrepo-com.svg',
    // 'special-defense': '/assets/svg/shield-svgrepo-com.svg',
   
  };